name: Tests

on: [push]

jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - run: xcodebuild -version
      - run: sudo xcode-select -switch /Applications/Xcode_11.app
      - run: xcodebuild -version
      - run: xcrun simctl list
      - run: ./gradlew objcTest
  jdk:
    name: JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: ['1.8', '9', '10', '11', '12', '13']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - run: ./gradlew jdk7test jdk8Test
