name: Tests

on: [push]

jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - run: xcodebuild -version
      - run: sudo xcode-select -switch /Applications/Xcode_11.app
      - run: xcodebuild -version
      - run: xcrun simctl list
      - run: ./gradlew objcTest
  jdk8:
    name: JDK 8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - run: ./gradlew jdk7test jdk8Test
  jdk13:
    name: JDK 13
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '13'
    - run: ./gradlew jdk7test jdk8Test
